server:
  port: 8081
  servlet:
    context-path: /hibernate

spring:
  h2:
    console.enabled: true
    console:
      path: /h2
  
  datasource:
    url: jdbc:h2:mem:testdb
    
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  
  jpa:
    show-sql: true
    properties:
      hibernate:  
        format_sql: false