server:
  port: 8081
  servlet:
    context-path: /jpa-data-rest

spring:
  h2:
    console.enabled: true
    console:
      path: /h2
  
  datasource:
    url: jdbc:h2:mem:testdb
    
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE      
      hibernate:  
        format_sql: false
        cache:
          use_second_level_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.internal.EhcacheRegionFactory
            

logging:
  level:
    net:
      sf:
        ehcache: debug            
            